---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    author: faizan
spec:
 ports:
   - targetPort: 5432
     port: 5432
 selector:
   name: mypostgres-pod
   author: faizan
...