---
apiVersion: v1
kind: Service
metadata:
  - name: myredis-service
    labels:
      name: myredis-service
      author: faizan
spec:
 type: ClusterIP
 ports:
   - targetPort: 6379
     port: 6379
 selector:
   name: redis-pod
   author: faizan
...