---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app-service
    author: faizan
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-pod
    author: faizan
...
