---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    author: faizan
spec:
 type: LoadBalancer
 ports:
   - targetport: 80
     port: 80
 selector:
   name: voting-pod
   author: faizan
...